version: "3.5"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment : 
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 123
      POSTGRES_DB : postgres
    volumes:
      - test_post_vol:/var/lib/postgresql/data
  backend :
    image : app2
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment :
       DATABASE_URL : "postgresql://postgres:123@postgres:5432/postgres"

volumes:
  test_post_vol: